### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by comfuzio**
Hi, I have added the how to update on docker.
I was looking for it myself and couldn't find, this is how I have updated mine.

### CODE REVIEW

**Comment by tpill90** [comment]
@comfuzio Did you mean to create this pull request against my repo?  This PR will only be merging changes into yours.

**Comment by comfuzio** [comment]
Yes, sorry new at this

**Comment by tpill90** [comment]
Message me when you have a second on discord, and I can help walk you through it

**Comment by comfuzio** [comment]
> Message me when you have a second on discord, and I can help walk you through it

Sure will do later when i am at home

**Pull request merged**
